#!/usr/bin/env bash
# =============================================================================
#  Hysteria2 (QUIC/UDP) server — install & configure. Sourceable module.
#
#  Can be used two ways:
#    1. Sourced as a module by install.sh (defines hysteria_setup, no side effects)
#    2. Run directly:  sudo ./hysteria.sh [port] [password]
#
#  Design notes:
#    - Reuses the node's TLS certificate (/opt/remnanode/nginx/...) — a single
#      certificate serves both the TCP (REALITY) and UDP (QUIC) listeners.
#    - Masquerade proxies unauthenticated traffic to the decoy web service,
#      so port scanners see a normal site instead of a QUIC endpoint.
#    - QUIC needs large UDP buffers: the installer's sysctl profile
#      (rmem_max/wmem_max = 64 MB) already exceeds Hysteria's 16 MB requirement.
# =============================================================================
if [[ -n "${_HYSTERIA_MODULE_LOADED:-}" ]]; then
    return 0 2>/dev/null || exit 0
fi
_HYSTERIA_MODULE_LOADED=1

HYSTERIA_PORT="${HYSTERIA_PORT:-443}"
HYSTERIA_CONFIG="/etc/hysteria/config.yaml"
HYSTERIA_SERVICE="hysteria-server.service"
HYSTERIA_CERT_DIR="${NODE_DIR:-/opt/remnanode}/nginx"

# --- logging: reuse the caller's helpers when sourced, plain echo otherwise ---
_h_info() { if declare -F info >/dev/null; then info "$*"; else echo "[INF] $*"; fi; }
_h_ok()   { if declare -F ok   >/dev/null; then ok   "$*"; else echo "[OK ] $*"; fi; }
_h_warn() { if declare -F warn >/dev/null; then warn "$*"; else echo "[WRN] $*"; fi; }
_h_die()  { if declare -F die  >/dev/null; then die  "$*"; else echo "[ERR] $*" >&2; exit 1; fi; }

hysteria_install() {
    if command -v hysteria >/dev/null 2>&1; then
        _h_ok "Hysteria2 already installed ($(hysteria version 2>/dev/null | grep -m1 -i '^version' || echo 'unknown version'))"
    else
        _h_info "Installing Hysteria2 from the official installer..."
        # Official installer: binary into /usr/local/bin, systemd units included
        curl -4 -fsSL https://get.hy2.sh/ | bash
        command -v hysteria >/dev/null 2>&1 || _h_die "Hysteria2 installation failed."
        _h_ok "Hysteria2 installed"
    fi

    systemctl enable --now "${HYSTERIA_SERVICE}" >/dev/null 2>&1 || true
}

hysteria_configure() {
    local port="${1:-$HYSTERIA_PORT}" password="${2:-}" cert_dir="${3:-$HYSTERIA_CERT_DIR}"

    if [[ -f "${HYSTERIA_CONFIG}" ]]; then
        _h_ok "Config already exists at ${HYSTERIA_CONFIG} — keeping it (update port/TLS there if needed)."
    else
        if [[ -z "$password" ]]; then
            password="$(openssl rand -hex 16)"
            _h_warn "No password given — generated one (store it, it is printed by the installer summary)."
        fi
        install -d -m 755 /etc/hysteria
        umask 077
        cat > "${HYSTERIA_CONFIG}" <<EOF
# Generated by the autonode installer. Server listens on UDP ${port} (QUIC).
listen: :${port}

tls:
  cert: ${cert_dir}/fullchain.pem
  key: ${cert_dir}/privkey.key

auth:
  type: password
  password: ${password}

# Unauthenticated/probe traffic is proxied to the decoy site
masquerade:
  type: proxy
  proxy:
    url: http://127.0.0.1:8080
    rewriteHost: true
EOF
        chmod 600 "${HYSTERIA_CONFIG}"
        _h_ok "Config written: UDP :${port}, masquerade -> decoy site"
    fi

    systemctl restart "${HYSTERIA_SERVICE}"
}

hysteria_verify() {
    local port="${1:-$HYSTERIA_PORT}" i
    for i in $(seq 1 10); do
        systemctl is-active --quiet "${HYSTERIA_SERVICE}" && break
        (( i == 10 )) && _h_warn "hysteria-server is not active — check: journalctl -u ${HYSTERIA_SERVICE}"
        sleep 1
    done
    if systemctl is-active --quiet "${HYSTERIA_SERVICE}"; then
        if ss -uln 2>/dev/null | grep -q ":${port} "; then
            _h_ok "Hysteria2 active, listening on UDP :${port}"
        else
            _h_warn "hysteria-server active but UDP :${port} not listening — check config/certificate."
        fi
    fi
}

hysteria_setup() {
    local port="${1:-$HYSTERIA_PORT}" password="${2:-}"
    hysteria_install
    hysteria_configure "$port" "$password"
    hysteria_verify "$port"
}

# --- direct execution ----------------------------------------------------------
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    set -euo pipefail
    [[ $EUID -eq 0 ]] || _h_die "hysteria.sh must be run as root."
    hysteria_setup "${1:-$HYSTERIA_PORT}" "${2:-}"
fi
